### PR TITLE
Fix most ruff complaints in the project

### PR DESCRIPTION
**Pull request by fabioseel**
I'm applying all the automatic fixes so that in the future our pull requests will be less cluttered with all of this and we can focus on the actual changes.

Still checking out whether I can fix some of the more advanced complaints, else we'll just have to merge it as is even though the linter might fail (as long as scan doesn't fail it should be fine)

I hope you currently don't have a branch with a lot of stuff open as this might be confusing to merge (but also might work out just fine).

### CODE REVIEW

**Comment by fabioseel** [comment]
If you look why it fails, it's 2 deprecated functions which might be deleted soon anyway so I did not bother fixing it but added a TODO comment instead.
Still think its worth merging this decently fast in order to be able to have cleaner commits in the future :)

**Comment by fabioseel** [comment]
I don't think you need to do an in depth review, most files are simply formatted etc

**Comment by alex404** [comment]
Once all checks pass I'll have a look

**Review by alex404 — COMMENTED** [review]
Alright sure. Hopefully this doesn't conflict with the merge request I just made. I'll try to merge this into my branch.

**Pull request merged**
